---
title: "Untitled"
author: "Christopher Gerstle"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(scipen = 999)

gc()

states <- c("GA","NC","TN","SC")
states.index <- seq(from=1, to=4)
tables <- c("TREE","SEEDLING")
tables.index <- c(1,2)

directory <- "D:/LAI Reparam/"

for (i in states.index){
  for (j in tables.index){
    state <- states[i]
    table <- tables[j]
    tablein <- read.csv(paste(directory,state,"/",state,"_",table,".csv", sep=""), header = TRUE, sep = ",")
    assign(x = paste(state,".",table, sep=""), value = tablein)
  }
}

hardwoods <- seq(from=25, to=43)
hardwood.S <- c(0.75, 0.81, 0.74, 0.77, 0.77, 0.83, 0.86, 0.83, 0.88, 0.82, 0.83, 0.82, 0.795, 0.88, 0.9, 0.91, 0.861, 0.78, 0.833)

softwoods <- seq(from=1, to=9)

SPGRPCDs <- c(1,2,3,4,5,6,7,8,9,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43)
SPGRPs<-c("longleaf_and_slash_pines","loblolly_pines","other_yellow_pines","eastern_white_and_red_pines","Jack_pine","spruce_and_balsam_fir","eastern_hemlock","cypress","other_softwoods","white_oaks_1","red_oaks_1","white_oaks_2","red_oaks_2","hickory","yellow_birch","hard_maples","soft_maples","beech","sweetgum","tupelo","ash","cottonwood_and_aspen","basswood","yellow-poplars","black_walnut","other_eastern_soft_hardwoods","other_easter_hard_hardwoods","eastern_noncommerical_hardwoods")
SPGRPCDs.index <- seq(from=1, to=length(SPGRPCDs))

S.table <- cbind(hardwoods, hardwood.S)
S.table <- as.data.frame(S.table)
colnames(S.table) <- c("SPGRPCD","Model.S")

SAPPS.TREE <- rbind(GA.TREE, NC.TREE, SC.TREE, TN.TREE)
SAPPS.SEEDLING <- rbind(GA.SEEDLING, NC.SEEDLING, SC.SEEDLING, TN.SEEDLING)

SAPPS.TREE$DIA.CM <- SAPPS.TREE$DIA * 2.54

SAPPS.TREE$HT.M <- SAPPS.TREE$HT / 3.2808

SAPPS.TREE$PLOT.YEAR <- paste(SAPPS.TREE$PLT_CN, SAPPS.TREE$INVYR, sep=".")

SAPPS.TREE <- SAPPS.TREE[SAPPS.TREE$STATUSCD == 1,]

SAPPS.TREE.HARDWOOD <- SAPPS.TREE[SAPPS.TREE$SPGRPCD %in% hardwoods,]

SAPPS.TREE.HARDWOOD <- merge(SAPPS.TREE.HARDWOOD, S.table)

SAPPS.TREE.HARDWOOD$LEAF.AREA.LN <- 0.2102 + (0.0586*SAPPS.TREE.HARDWOOD$DIA.CM) + (4.0202*SAPPS.TREE.HARDWOOD$Model.S)

SAPPS.TREE.HARDWOOD$LEAF.AREA <- exp(SAPPS.TREE.HARDWOOD$LEAF.AREA.LN)

SAPPS.PLOT.HARDWOOD.LEAFAREA <- aggregate(SAPPS.TREE.HARDWOOD$LEAF.AREA, by=list(PLOT.YEAR=SAPPS.TREE.HARDWOOD$PLOT.YEAR), FUN=sum)

colnames(SAPPS.PLOT.HARDWOOD.LEAFAREA) <- c("PLOT.YEAR","HARDWOOD.LEAFAREA")

SAPPS.TREE.SOFTWOOD <- SAPPS.TREE[SAPPS.TREE$SPGRPCD %in% softwoods,]

SAPPS.TREE.SOFTWOOD$LEAF.BIOMASS.KG <- 0.0621*(SAPPS.TREE.SOFTWOOD$DIA.CM^1.505)

SAPPS.TREE.SOFTWOOD$LEAF.BIOMASS.G <- SAPPS.TREE.SOFTWOOD$LEAF.BIOMASS.KG * 1000

SAPPS.TREE.SOFTWOOD$SURFACEAREA.TOTAL <- SAPPS.TREE.SOFTWOOD$LEAF.BIOMASS.G / 227

SAPPS.TREE.SOFTWOOD$SURFACEAREA.HALF <- SAPPS.TREE.SOFTWOOD$SURFACEAREA.TOTAL / 2

SAPPS.PLOT.SOFTWOOD.LEAFAREA <- aggregate(SAPPS.TREE.SOFTWOOD$SURFACEAREA.HALF, by=list(PLOT.YEAR=SAPPS.TREE.SOFTWOOD$PLOT.YEAR), FUN=sum)

colnames(SAPPS.PLOT.SOFTWOOD.LEAFAREA) <- c("PLOT.YEAR","SOFTWOOD.LEAFAREA")

SAPPS.PLOT.TOTAL.LEAFAREA <- merge(SAPPS.PLOT.HARDWOOD.LEAFAREA, SAPPS.PLOT.SOFTWOOD.LEAFAREA, all=T)

SAPPS.PLOT.TOTAL.LEAFAREA[is.na(SAPPS.PLOT.TOTAL.LEAFAREA)] <- 0

SAPPS.PLOT.TOTAL.LEAFAREA$TOTAL.LEAFAREA <- SAPPS.PLOT.TOTAL.LEAFAREA$HARDWOOD.LEAFAREA + SAPPS.PLOT.TOTAL.LEAFAREA$SOFTWOOD.LEAFAREA

SAPPS.PLOT.TOTAL.LEAFAREA$PLOT.LAI <- SAPPS.PLOT.TOTAL.LEAFAREA$TOTAL.LEAFAREA / 672.469876708172

SAPPS.SEEDLING$PLOT.YEAR <- paste(SAPPS.SEEDLING$PLT_CN, SAPPS.SEEDLING$INVYR, sep=".")
```

```{r}
Model.Species <- read.csv(paste(directory,"ModelSpeciesCodes.csv", sep=""),header=T, sep=",")
Model.Species$LongCom.char <- as.character(Model.Species$LongCom)
Model.Species.index <- seq(from=1, to=length(Model.Species$SPCD))

for (i in Model.Species.index){
  SPCD <- Model.Species$SPCD[i]
  Table <- SAPPS.SEEDLING[SAPPS.SEEDLING$SPCD == SPCD,]
  if(nrow(Table) == 0) next
  Sums <- aggregate(Table$TREECOUNT, by=list(PLOT.YEAR = Table$PLOT.YEAR), FUN=sum)
  colnames(Sums) <- c("PLOT.YEAR", Model.Species$LongCom.char[i])
  SAPPS.PLOT.TOTAL.LEAFAREA <- merge(SAPPS.PLOT.TOTAL.LEAFAREA, Sums, all.x = T)
}

SAPPS.PLOT.TOTAL.LEAFAREA[is.na(SAPPS.PLOT.TOTAL.LEAFAREA)] <- 0

write.csv(SAPPS.PLOT.TOTAL.LEAFAREA, file = paste(directory,"SAPPS.PLOT.TOTAL.LEAFAREA.csv", sep=""))
```

```{r}
mins <- seq(from=0, to= 19.8, by =0.2)
maxs <- seq(from=0.2, to = 20.0, by=0.2)
histogram.index <- seq(from=1, to=100)

SAPPS.histogram <- as.data.frame(cbind(mins, maxs))
colnames(SAPPS.histogram) <- c("min","max")


for (i in Model.Species.index){
    SP.needed <- Model.Species$LongCom.char[i]
    columns.needed.vec <- c("PLOT.LAI", SP.needed)
    columns.needed <- SAPPS.PLOT.TOTAL.LEAFAREA[names(SAPPS.PLOT.TOTAL.LEAFAREA)[names(SAPPS.PLOT.TOTAL.LEAFAREA) %in% columns.needed.vec]]
    mean.inrange <- c()
    for (j in histogram.index){
    min <- mins[j]
    max <- maxs[j]
    subset <- columns.needed[columns.needed$PLOT.LAI >= min & columns.needed$PLOT.LAI < max,]
    final.column <- subset[names(subset)[names(subset) %in% SP.needed]]
    final.column.vec <- as.vector(final.column)
    mean.inrange[j] <- mean(final.column[,SP.needed])
    }
    SAPPS.histogram[,SP.needed] <- mean.inrange
}

for (i in Model.Species.index){
  SP.needed <- Model.Species$LongCom.char[i]
  SPCD.needed <- Model.Species$SPCD[i]
  barplot(height = SAPPS.histogram[,SP.needed], names.arg = SAPPS.histogram$max, main = SP.needed, xlab = "LAI",ylab="Seedlings/plot")
}
```



```{r}

library(spatstat)
species <- c()
weighted.LAI.mean <- c()
weighted.LAI.var <- c()
weighted.LAI.SD <- c()
weighted.LAI.log.mean <- c()
weighted.LAI.log.var <- c()
weighted.LAI.log.SD <- c()

Table.NoOutliers <- SAPPS.PLOT.TOTAL.LEAFAREA[SAPPS.PLOT.TOTAL.LEAFAREA$PLOT.LAI<100,]
Table.NoOutliers$PLOT.LAI.LOG <- log(Table.NoOutliers$PLOT.LAI)

for (i in Model.Species.index){
  SP.needed <- Model.Species$LongCom.char[i]
  PLOT.LAI <- Table.NoOutliers$PLOT.LAI
  PLOT.LAI.LOG <- Table.NoOutliers$PLOT.LAI.LOG
  PLOT.SEEDLINGS <- Table.NoOutliers[,SP.needed]
  PLOT.SEEDLINGS.TOTAL <- sum(PLOT.SEEDLINGS)
  weights <- PLOT.SEEDLINGS/PLOT.SEEDLINGS.TOTAL
  Weighted.LAI.mean <- weighted.mean(x = PLOT.LAI, w = weights)
  Weighted.LAI.var <- weighted.var(x=PLOT.LAI, w=weights)
  Weighted.LAI.log.mean <- weighted.mean(x = PLOT.LAI.LOG, w = weights)
  Weighted.LAI.log.var <- weighted.var(x=PLOT.LAI.LOG, w=weights)
  species[i] <- SP.needed
  weighted.LAI.mean[i] <- Weighted.LAI.mean
  weighted.LAI.var[i] <- Weighted.LAI.var
  weighted.LAI.SD[i] <- sqrt(Weighted.LAI.var)
  weighted.LAI.log.mean[i] <- Weighted.LAI.log.mean
  weighted.LAI.log.var[i] <- Weighted.LAI.log.var
  weighted.LAI.log.SD[i] <- sqrt(Weighted.LAI.log.var)
}

weighted.mean.LAI.table <- data.frame(species, weighted.LAI.mean, weighted.LAI.var, weighted.LAI.SD, weighted.LAI.log.mean, weighted.LAI.log.var, weighted.LAI.log.SD)

grid <- seq(0,20,.1)
plot(grid,dlnorm(grid,-0.08653947,1.3804560),type="l",xlab="LAI",ylab="f(x)", col="blue")
lines(grid,dlnorm(grid,1.39746695, 0.7739607), col="purple")
lines(grid,dlnorm(grid,1.94351101, 0.6928515), col="red")
legend("topright", legend=c("Loblolly Pine","White Oak","Sugar Maple"), col=c("blue","purple","red"), lty=1)

for (i in Model.Species.index){
  SP.needed <- weighted.mean.LAI.table$species[i]
  logmean <- weighted.mean.LAI.table$weighted.LAI.log.mean[i]
  logsd <- weighted.mean.LAI.table$weighted.LAI.log.SD[i]
  plot(grid,dlnorm(grid,logmean,logsd),type="l",xlab="LAI",ylab="f(x)", col="blue", main=SP.needed, ylim=c(0,0.8))
}
```

